### PR TITLE
Added multithreading test that hangs.

### PR DESCRIPTION
**Pull request by bveldhoen**
Added a unit test in order to reproduce a deadlock when executing synchronous SET and DEL commands concurrently. (You might argue why we do synchronous commands concurrently, but that's the nature of our applications at the moment). Anyways, this looks like a serious issue that needs fixing.
I have added some output files containing more information:
*pstack.output:* Contains the pstack output of the test_redox process after it deadlocks. From the thread stacks, it's clear that one thread (#2) deadlocks in a wait of the condition_variable (line 43 in command.cpp).
*monitor.output:* Contains the redis monitor output. This shows that the thread executing the SET commands executes to completion, but the thread executing the DEL command deadlocks.
*redis.output:* Contains the output of executing SET and DEL commands concurrently using redis-cli. This doesn't show a deadlock (as expected).

Executing the unit test reliably reproduces the deadlock on my machine.

### CODE REVIEW

**Comment by bveldhoen** [comment]
It may be worth investigating/implementing (as an addition to a proper bugfix for this issue) a timeout while waiting for the redis result (use condition_variable::wait_for(...) instead of condition_variable::wait()?). Note I do not mean this as a proposed bug fix, but rather as an improvement on top of a proper bugfix.

**Comment by bveldhoen** [comment]
I added a commit that fixes the issue in the unit test. An atomic variable was increased, but the value after increase wasn't stored, which may lead to multiple commands having the same id. By using fetch_add (which is used by the operators (++, --, etc.) of std::atomic<...>), the value after increase is stored and is unique for each command. I haven't checked for other usages of std::atomic<...> throughout the redox codebase, but there may be other places where similar issues occur.

**Comment by hmartiro** [comment]
Thank you for doing this! I unfortunately don't get to use redox in my job, and so haven't had time to make some long-needed improvements. I will review your change and look for other similar cases as soon as I can.

**Comment by bveldhoen** [comment]
Hi Hayk,
 
Apparently bdallas and Collin Hockey have also run into some concurrency
problems, and uploaded a pull request. I suggest you take their pull request, as
it contains a similar fix for the command id and some other good fixes as well.
One thing I'd like to add to their pull request is the fact that by using
mutexes and locks to guard the access to some of the atomic variables, I think
those can be changed into regular non-atomic variables.
 
When do you think you can pull the changes from bdallas in? (I could work with a
temporary branch, but I prefer to wait until the changes have been merged into
your main branch).
 
Many thanks!
Kind regards,
Bram Veldhoen

**Comment by hmartiro** [comment]
Hi Bram, I am hoping to bring in these changes this week. Thanks for the suggestions.

**Comment by hmartiro** [comment]
Hey, check out https://github.com/hmartiro/redox/pull/27. I added your test and it passes in the branch. I will merge that in in a couple of days, letting you and bdallas take a look. Thanks. I did switch to non-atomic variables.

With regards to the wait_for, a synchronous command with a timeout could be a useful feature, I agree.

**Pull request closed without merging**
