### PR TITLE
Added lastError() to Command.

### PR DESCRIPTION
**Pull request by bveldhoen**
Hi Hayk!
Cool project! We're very seriously looking into using it. I have some ideas to add functionality based on our needs.

As a start, I added a way to retrieve the Redis error by setting and exposing the last error that occurred while executing a command. Pls. let me know if it is in line with what you'd expect!

Cheers,
Bram Veldhoen

### CODE REVIEW

**Comment by hmartiro** [comment]
Hi Bram! I'll take a closer look in the next couple of days, but it generally looks good.

**Comment by bveldhoen** [comment]
Closing so I can include the other changes.

**Comment by bveldhoen** [comment]
Hi Hayk,
 
I've added a couple more commits w.r.t. stability and cmake stuff, pls have a
look. I retracted my previous pull request and issued a new one containing my
recent changes.
 
I also have a couple of questions about the way forward. Could you pls. have a
look (when you have the time, off course)?
 
- How about using exceptions throughout? There already seem to be a couple of
places where exceptions are used, so why not in other places? This would improve
code quality and conciseness (imo).
- In our own library, I've added an implementation on top of Redox in a class
called RedisClient. That code uses variadic templates (and macros) to add the
Redis commands as member functions. I think it could be in the Redox class
instead of in a wrapper class (such as RedisClient). Would you object to
variadic templates and macros? It may need C++14.
- We've experienced some serious issues with the known issue regarding segfaults
while disconnecting when a command is in progress. Would it be possible to
provide a fix, or give some pointers where to start looking?
- I've experienced a couple of serious hangs of my entire VM (had to force shut
it down), seeming to originate from line 256 in client.cpp ( function
Redox::runEventLoop() ):
 

ev_run(evloop_);

 

Did you ever experience this before? If yes, do you know if there's something I
can do in order to prevent it? I'll try to come up with a unit test to reproduce
the issue in the mean time.

 

Thanks,

Bram Veldhoen

**Comment by hmartiro** [comment]
Bram, I've merged your additions with some minor tweaks. Thanks.

-How about using exceptions throughout? There already seem to be a couple of places where exceptions are used, so why not in other places? This would improve code quality and conciseness (imo).

Could you give examples of what you propose?

- In our own library, I've added an implementation on top of Redox in a class called RedisClient. That code uses variadic templates (and macros) to add the Redis commands as member functions. I think it could be in the Redox class instead of in a wrapper class (such as RedisClient). Would you object to variadic templates and macros? It may need C++14. 

I'd love to see an example of what you mean. I think C++14 is a bit prohibitive right now, but anything C++11 I'd enjoy taking a look at. C++14 would be great to have templated member variables, but I think it's a little too soon. In particular, the command maps have to have awkward function specializations.

- We've experienced some serious issues with the known issue regarding segfaults while disconnecting when a command is in progress. Would it be possible to provide a fix, or give some pointers where to start looking? - I've experienced a couple of serious hangs of my entire VM (had to force shut it down), seeming to originate from line 256 in client.cpp ( function Redox::runEventLoop() ): ev_run(evloop_); Did you ever experience this before? If yes, do you know if there's something I can do in order to prevent it? I'll try to come up with a unit test to reproduce the issue in the mean time.

A unit test would be great to pinpoint what's happening. I struggled with disconnect issues for a while and would like to see it fixed. Can you show me what you're running and the backtraces on all threads?

**Pull request closed without merging**
